services:
  - type: web
    name: nexachat
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: SW_ENABLED
        value: "true"
      - key: SW_CEREBRO_ADDR
        value: "PASTE_YOUR_NGROK_URL_HERE"
      - key: SW_APP_ID
        value: "nexachat-prod"
      - key: SW_LOG_ONLY
        value: "false"
